const coursesCard = [
    {
      id: 1,
      title: "Mathematics BAC 2025",
      description: "This course covers all bachelor mathematics before the final exam.",
      type: "Face to Face",
      location: "Boumerdes",
      price: 5000,
      status: "open",
      student_max: 60,
      student_current: 38,
      likes: 27,
      stars: 5,
    },
    {
      id: 2,
      title: "Physics BAC 2025",
      description: "This course covers all bachelor physics before the final exam.",
      type: "Online",
      location: "Boumerdes",
      price: 7000,
      status: "close",
      student_max: 60,
      student_current: 38,
      likes: 27,
      stars: 5,
    },
    {
      id: 3,
      title: "Chemistry BAC 2025",
      description: "This course covers all bachelor chemistry before the final exam.",
      type: "Face to Face",
      location: "Boumerdes",
      price: 5500,
      status: "open",
      student_max: 60,
      student_current: 42,
      likes: 15,
      stars: 4,
    },
    {
      id: 4,
      title: "Biology BAC 2025",
      description: "This course covers all bachelor biology before the final exam.",
      type: "Face to Face",
      location: "Boumerdes",
      price: 5000,
      status: "open",
      student_max: 60,
      student_current: 38,
      likes: 27,
      stars: 5,
    },
    {
      id: 5,
      title: "English BAC 2025",
      description: "This course covers all bachelor English before the final exam.",
      type: "Face to Face",
      location: "Boumerdes",
      price: 4500,
      status: "open",
      student_max: 60,
      student_current: 40,
      likes: 30,
      stars: 5,
    },
    {
      id: 6,
      title: "History BAC 2025",
      description: "This course covers all bachelor history before the final exam.",
      type: "Online",
      location: "Boumerdes",
      price: 4000,
      status: "open",
      student_max: 60,
      student_current: 32,
      likes: 25,
      stars: 4,
    },
    {
      id: 7,
      title: "Geography BAC 2025",
      description: "This course covers all bachelor geography before the final exam.",
      type: "Face to Face",
      location: "Boumerdes",
      price: 4700,
      status: "open",
      student_max: 60,
      student_current: 36,
      likes: 20,
      stars: 4,
    },
    {
      id: 8,
      title: "Philosophy BAC 2025",
      description: "This course covers all bachelor philosophy before the final exam.",
      type: "Face to Face",
      location: "Boumerdes",
      price: 4800,
      status: "open",
      student_max: 60,
      student_current: 38,
      likes: 28,
      stars: 5,
    },
    {
      id: 9,
      title: "Economics BAC 2025",
      description: "This course covers all bachelor economics before the final exam.",
      type: "Face to Face",
      location: "Boumerdes",
      price: 5000,
      status: "open",
      student_max: 60,
      student_current: 38,
      likes: 27,
      stars: 5,
    },
    {
        id: 10,
        title: "Economics BAC 2025",
        description: "This course covers all bachelor economics before the final exam.",
        type: "Face to Face",
        location: "Boumerdes",
        price: 5000,
        status: "open",
        student_max: 60,
        student_current: 38,
        likes: 2,
        stars: 3,
      },
      {
        id: 11,
        title: "Economics BAC 2025",
        description: "This course covers all bachelor economics before the final exam.",
        type: "Face to Face",
        location: "Boumerdes",
        price: 5000,
        status: "open",
        student_max: 60,
        student_current: 38,
        likes: 7,
        stars: 5,
      },
  ];
  
  export default coursesCard;
  